In [1]:
import pandas as pd

In [2]:
import math

In [3]:
MCI_flights_df = pd.read_csv('../../Starter/Resources/MCI_21-23.csv').drop(['Unnamed: 0'],axis=1)

In [4]:
MCI_flights_df=MCI_flights_df.replace({'Status': {'On Time': 0, 'Delayed': 1}})
MCI_flights_df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_UNIQUE_CARRIER,MKT_CARRIER_FL_NUM,TAIL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,...,ARR_DELAY_NEW,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,Status,DATE,DEST_LAT,DEST_LON,ORIGIN_LAT,ORIGIN_LON
0,2021,1,1,5,AA,3397,N268NN,MCI,Kansas City,Missouri,...,4.0,0.0,1200-1259,0.0,0,2021-01-01,41.875562,-87.624421,39.100105,-94.578142
1,2021,1,1,5,AA,3740,N289MW,MCI,Kansas City,Missouri,...,144.0,9.0,1100-1159,0.0,1,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
2,2021,1,1,5,AA,4075,N220NN,MCI,Kansas City,Missouri,...,12.0,0.0,1900-1959,0.0,0,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
3,2021,1,1,5,AA,4119,N282NN,MCI,Kansas City,Missouri,...,5.0,0.0,1700-1759,0.0,0,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
4,2021,1,1,5,AA,4221,N277NN,MCI,Kansas City,Missouri,...,3.0,0.0,0900-0959,0.0,0,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259853,2023,12,31,7,WN,704,N8624J,DAL,Dallas,Texas,...,12.0,0.0,2200-2259,0.0,1,2023-12-31,39.100105,-94.578142,32.776272,-96.796856
259854,2023,12,31,7,WN,714,N7883A,DAL,Dallas,Texas,...,0.0,-1.0,0800-0859,0.0,0,2023-12-31,39.100105,-94.578142,32.776272,-96.796856
259855,2023,12,31,7,WN,790,N7839A,MKE,Milwaukee,Wisconsin,...,0.0,-1.0,1100-1159,0.0,0,2023-12-31,39.100105,-94.578142,43.034993,-87.922497
259856,2023,12,31,7,WN,846,N8567Z,DCA,Washington,Virginia,...,13.0,0.0,1400-1459,0.0,1,2023-12-31,39.100105,-94.578142,38.895037,-77.036543
259857,2023,12,31,7,WN,894,N965WN,ABQ,Albuquerque,New Mexico,...,0.0,-1.0,1600-1659,0.0,1,2023-12-31,39.100105,-94.578142,35.084103,-106.650985

In [6]:
MCI_flights_df.columns

Index(['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER',
       'MKT_CARRIER_FL_NUM', 'TAIL_NUM', 'ORIGIN', 'ORIGIN_CITY_NAME',
       'ORIGIN_STATE_NM', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_NM',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY_NEW', 'DEP_DELAY_GROUP',
       'DEP_TIME_BLK', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN',
       'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY_NEW', 'ARR_DELAY_GROUP',
       'ARR_TIME_BLK', 'CANCELLED', 'Status', 'DATE', 'DEST_LAT', 'DEST_LON',
       'ORIGIN_LAT', 'ORIGIN_LON'],
      dtype='object')

In [19]:
flight_dummies = pd.get_dummies(MCI_origin_df[['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER',
                                                'DEST', 'DEST_STATE_NM','CRS_DEP_TIME','TAXI_OUT','TAXI_IN','DEP_DELAY_GROUP', 'Status']])
flight_dummies

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,CRS_DEP_TIME,TAXI_OUT,TAXI_IN,DEP_DELAY_GROUP,CANCELLED,Status,...,DEST_STATE_NM_North Carolina,DEST_STATE_NM_Oregon,DEST_STATE_NM_Pennsylvania,DEST_STATE_NM_South Carolina,DEST_STATE_NM_Tennessee,DEST_STATE_NM_Texas,DEST_STATE_NM_Utah,DEST_STATE_NM_Virginia,DEST_STATE_NM_Washington,DEST_STATE_NM_Wisconsin
0,2021,1,1,5,1050,29.0,7.0,-1.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,2021,1,1,5,928,35.0,10.0,8.0,0.0,1,...,0,0,0,0,0,1,0,0,0,0
2,2021,1,1,5,1728,25.0,14.0,-1.0,0.0,0,...,0,0,0,0,0,1,0,0,0,0
3,2021,1,1,5,1530,23.0,15.0,-1.0,0.0,0,...,0,0,0,0,0,1,0,0,0,0
4,2021,1,1,5,718,39.0,8.0,-1.0,0.0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129816,2023,12,31,7,930,7.0,3.0,-1.0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
129817,2023,12,31,7,855,7.0,4.0,-1.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
129818,2023,12,31,7,1510,8.0,4.0,0.0,0.0,1,...,0,0,0,0,0,1,0,0,0,0
129819,2023,12,31,7,1730,11.0,5.0,0.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
129820,2023,12,31,7,1345,9.0,6.0,0.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0

In [23]:
status_corr = flight_dummies.corr()['DEP_DELAY_GROUP']
status_corr

YEAR                        0.042099
MONTH                      -0.003279
DAY_OF_MONTH                0.007369
DAY_OF_WEEK                 0.023888
CRS_DEP_TIME                0.164441
                              ...
DEST_STATE_NM_Texas         0.014990
DEST_STATE_NM_Utah         -0.023362
DEST_STATE_NM_Virginia     -0.013035
DEST_STATE_NM_Washington   -0.026303
DEST_STATE_NM_Wisconsin    -0.004045
Name: DEP_DELAY_GROUP, Length: 102, dtype: float64

In [21]:
flight_dummies.columns

Index(['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'CRS_DEP_TIME',
       'TAXI_OUT', 'TAXI_IN', 'DEP_DELAY_GROUP', 'CANCELLED', 'Status',
       ...
       'DEST_STATE_NM_North Carolina', 'DEST_STATE_NM_Oregon',
       'DEST_STATE_NM_Pennsylvania', 'DEST_STATE_NM_South Carolina',
       'DEST_STATE_NM_Tennessee', 'DEST_STATE_NM_Texas', 'DEST_STATE_NM_Utah',
       'DEST_STATE_NM_Virginia', 'DEST_STATE_NM_Washington',
       'DEST_STATE_NM_Wisconsin'],
      dtype='object', length=102)

In [24]:
i = 0
for item in status_corr:
    print(i,'%.2f'%item)
    i+=1

0 0.04
1 -0.00
2 0.01
3 0.02
4 0.16
5 0.04
6 0.01
7 1.00
8 nan
9 0.58
10 -0.01
11 -0.02
12 0.03
13 -0.07
14 0.02
15 0.03
16 0.02
17 -0.03
18 0.07
19 -0.00
20 -0.03
21 -0.00
22 0.01
23 0.00
24 0.00
25 0.00
26 0.00
27 -0.00
28 -0.00
29 0.02
30 -0.01
31 0.02
32 0.02
33 -0.03
34 -0.00
35 -0.01
36 0.02
37 0.01
38 -0.01
39 -0.02
40 0.01
41 0.01
42 0.03
43 0.02
44 -0.01
45 -0.00
46 0.02
47 0.01
48 -0.01
49 -0.00
50 -0.02
51 -0.00
52 0.00
53 0.02
54 -0.01
55 0.01
56 0.03
57 -0.01
58 0.01
59 0.01
60 -0.00
61 0.00
62 0.01
63 0.01
64 -0.00
65 -0.03
66 0.00
67 -0.01
68 -0.02
69 -0.00
70 0.01
71 -0.00
72 0.01
73 0.01
74 0.01
75 0.02
76 0.02
77 0.03
78 -0.03
79 -0.01
80 0.01
81 -0.00
82 -0.00
83 0.00
84 0.00
85 -0.03
86 -0.02
87 -0.00
88 0.03
89 -0.01
90 -0.00
91 -0.01
92 -0.00
93 0.01
94 -0.01
95 0.00
96 0.01
97 0.01
98 -0.02
99 -0.01
100 -0.03
101 -0.00

In [ ]:
correlation_matrix = flight_dummies.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

In [ ]:
MCI_flights_df = MCI_flights_df.astype({'DAY_OF_MONTH': 'object','DEP_DELAY_GROUP':'object'})

In [ ]:
MCI_flights_df.columns

In [ ]:
MCI_flights_df['Status'].describe()

In [ ]:
MCI_flights_df.loc[MCI_flights_df['MKT_UNIQUE_CARRIER']=='WN']['Status'].value_counts()

MCI_flights_df.to_csv('../Resources/MCI_21-23.csv')

In [9]:
MCI_origin_df=MCI_flights_df.loc[MCI_flights_df['ORIGIN'] == 'MCI']
MCI_dest_df=MCI_flights_df.loc[MCI_flights_df['DEST'] == 'MCI']
MCI_2021_df=MCI_flights_df.loc[MCI_flights_df['YEAR'] == 2021]
MCI_2022_df=MCI_flights_df.loc[MCI_flights_df['YEAR'] == 2022]
MCI_2023_df=MCI_flights_df.loc[MCI_flights_df['YEAR'] == 2023]
MCI_WN_df=MCI_flights_df.loc[MCI_flights_df['MKT_UNIQUE_CARRIER'] == 'WN'].loc[MCI_flights_df['ORIGIN'] == 'MCI']
MCI_notWN_df=MCI_flights_df.loc[MCI_flights_df['MKT_UNIQUE_CARRIER'] != 'WN']

In [ ]:
X = MCI_flights_df[['YEAR','MONTH','DAY_OF_MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER', 'ORIGIN', 'DEST', 'DEP_TIME_BLK']]

In [ ]:
X.dtypes

In [ ]:
X = X.replace({'YEAR': {2021:'old',2022:'old',2023:'new'}})

In [ ]:
MCI_flights_df.columns

In [ ]:
y = MCI_flights_df['Status']

In [ ]:
y.value_counts()

In [ ]:
X_dummies = pd.get_dummies(X[['YEAR','MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER',
       'ORIGIN', 'DEST', 'DEP_TIME_BLK']])

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from keras.layers import Dense, Dropout

In [ ]:
scaler = StandardScaler()
scaler.fit(flight_dummies)
transformed_data = scaler.transform(flight_dummies)
# Creating a DataFrame with with the scaled data
transformed_data_df = pd.DataFrame(transformed_data)

# Display sample data
transformed_data_df

In [ ]:
transformed_data_df.corr()

In [ ]:
import seaborn as sns

In [ ]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np
pca = PCA().fit(transformed_data_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

In [ ]:
from sklearn.decomposition import PCA
# Create a PCA model
nc = 15
pca = PCA(n_components=nc)
pca_data = pca.fit_transform(transformed_data_df)
pca_dict = {}
for i in range(0,nc):
    pca_dict[f'pca{i+1}']=pca_data[:,i]
# Display sample data
pca_df = pd.DataFrame(pca_dict)
pca_df

In [ ]:
y

In [ ]:
X_dummies.join(y).corr()

In [ ]:
X_sample = X_dummies.head(1)
X_sample

In [ ]:
X_sample.to_csv('../Resources/X_dummies.csv')

In [ ]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X_dummies, y,test_size=0.30, random_state=78)

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=64, activation="relu", input_dim=len(X_dummies.columns)))
# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=128, activation="relu"))
nn_model.add(Dropout(0.2))
#nn_model.add(tf.keras.layers.Dense(units=128, activation="relu"))
#nn_model.add(Dropout(0.2))
# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=512, activation="relu"))
nn_model.add(Dropout(0.5))
# Third hidden layer
#nn_model.add(tf.keras.layers.Dense(units=1024, activation="relu"))
#nn_model.add(Dropout(0.7))
# Third hidden layer
#nn_model.add(tf.keras.layers.Dense(units=512, activation="sigmoid"))
nn_model.add(Dropout(0.5))
nn_model.add(tf.keras.layers.Dense(units=64, activation="sigmoid"))
#nn_model.add(Dropout(0.8))
# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

In [ ]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = nn_model.fit(X_train, y_train, epochs=50)

In [ ]:
model_loss, model_accuracy = nn_model.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
predictions = nn_model.predict(X_test)
predictions

In [ ]:
y_test.describe()

In [ ]:
predictions_df = pd.DataFrame(predictions.tolist())
predictions_df.describe()

In [ ]:
predictions_df

In [ ]:
nn_model.save('../nn_model.keras')

In [ ]:
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(random_state=1)

# Fit the model using training data
model.fit(X_train, y_train)

In [ ]:
model.score(X_train, y_train)

In [ ]:
# Make a prediction using the testing data
predictions = model.predict(X_test)
# Print the balanced_accuracy score of the model
balanced_accuracy_score(y_test,predictions)

In [ ]:
# Generate a confusion matrix for the model
confusion_matrix(y_test,predictions)

In [ ]:
# Print the classification report for the model
tn, fp, fn, tp = confusion_matrix(y_test, predictions).ravel()
accuracy = (tp + tn) / (tp + fp + tn + fn)
accuracy

In [ ]:
tp

In [ ]:
tn

In [ ]:
fp

In [ ]:
fn

In [ ]:
lr_predictions = model.predict(X_test)
lr_predictions

In [ ]:
X_test['Prediction'] = list(lr_predictions)

In [ ]:
X_test