In [1]:
import pandas as pd

In [2]:
MCI_flights_df = pd.read_csv('../Resources/MCI_21-23.csv').drop(['Unnamed: 0'],axis=1)

In [3]:
MCI_flights_df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_UNIQUE_CARRIER,MKT_CARRIER_FL_NUM,TAIL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,...,ARR_DELAY_NEW,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,Status,DATE,DEST_LAT,DEST_LON,ORIGIN_LAT,ORIGIN_LON
0,2021,1,1,5,AA,3397,N268NN,MCI,Kansas City,Missouri,...,4.0,0.0,1200-1259,0.0,On Time,2021-01-01,41.875562,-87.624421,39.100105,-94.578142
1,2021,1,1,5,AA,3740,N289MW,MCI,Kansas City,Missouri,...,144.0,9.0,1100-1159,0.0,Delayed,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
2,2021,1,1,5,AA,4075,N220NN,MCI,Kansas City,Missouri,...,12.0,0.0,1900-1959,0.0,On Time,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
3,2021,1,1,5,AA,4119,N282NN,MCI,Kansas City,Missouri,...,5.0,0.0,1700-1759,0.0,On Time,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
4,2021,1,1,5,AA,4221,N277NN,MCI,Kansas City,Missouri,...,3.0,0.0,0900-0959,0.0,On Time,2021-01-01,32.753177,-97.332746,39.100105,-94.578142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259853,2023,12,31,7,WN,704,N8624J,DAL,Dallas,Texas,...,12.0,0.0,2200-2259,0.0,Delayed,2023-12-31,39.100105,-94.578142,32.776272,-96.796856
259854,2023,12,31,7,WN,714,N7883A,DAL,Dallas,Texas,...,0.0,-1.0,0800-0859,0.0,On Time,2023-12-31,39.100105,-94.578142,32.776272,-96.796856
259855,2023,12,31,7,WN,790,N7839A,MKE,Milwaukee,Wisconsin,...,0.0,-1.0,1100-1159,0.0,On Time,2023-12-31,39.100105,-94.578142,43.034993,-87.922497
259856,2023,12,31,7,WN,846,N8567Z,DCA,Washington,Virginia,...,13.0,0.0,1400-1459,0.0,Delayed,2023-12-31,39.100105,-94.578142,38.895037,-77.036543
259857,2023,12,31,7,WN,894,N965WN,ABQ,Albuquerque,New Mexico,...,0.0,-1.0,1600-1659,0.0,Delayed,2023-12-31,39.100105,-94.578142,35.084103,-106.650985

In [4]:
MCI_flights_df.columns

Index(['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER',
       'MKT_CARRIER_FL_NUM', 'TAIL_NUM', 'ORIGIN', 'ORIGIN_CITY_NAME',
       'ORIGIN_STATE_NM', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_NM',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY_NEW', 'DEP_DELAY_GROUP',
       'DEP_TIME_BLK', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN',
       'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY_NEW', 'ARR_DELAY_GROUP',
       'ARR_TIME_BLK', 'CANCELLED', 'Status', 'DATE', 'DEST_LAT', 'DEST_LON',
       'ORIGIN_LAT', 'ORIGIN_LON'],
      dtype='object')

In [ ]:
cols = ['YEAR', 'MONTH', 'DAY_OF_MONTH', 'TAIL_NUM','MKT_CARRIER_FL_NUM','DEP_TIME_BLK']
more_cols = ['YEAR', 'MONTH', 'DAY_OF_MONTH',  'MKT_UNIQUE_CARRIER','TAIL_NUM','DEP_TIME_BLK','ORIGIN','DEST','DEP_DELAY_NEW','ARR_DELAY_NEW']
MCI_flights_df.loc[(MCI_flights_df['MKT_UNIQUE_CARRIER'] == 'WN')].sort_values(by = cols)[more_cols].head(50)

In [6]:
MCI_origin_df=MCI_flights_df.loc[MCI_flights_df['ORIGIN'] == 'MCI']
MCI_dest_df=MCI_flights_df.loc[MCI_flights_df['DEST'] == 'MCI']

In [56]:
tails = []
for row in MCI_origin_df.iterrows():
    tail_group = (row[1]['TAIL_NUM'][-1])
    tails.append(tail_group)

In [57]:
MCI_origin_df['TAIL_NUM'] = tails

In [59]:
MCI_origin_df['TAIL_NUM'].unique()

array(['A', 'V', 'N', 'Z', 'B', 'S', 'F', 'W', 'C', 'X', 'T', 'H', 'R',
       'M', 'E', 'Q', 'D', 'K', 'U', 'L', 'G', 'J', 'P', '5'],
      dtype=object)

In [8]:
avg_arr_delay_dict = MCI_dest_df.groupby(['MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER', 'DEP_TIME_BLK'])['ARR_DELAY_NEW'].mean()
avg_arr_delay_dict

MONTH  DAY_OF_WEEK  MKT_UNIQUE_CARRIER  DEP_TIME_BLK
1      1            WN                  0001-0559        1.833333
                                        0600-0659        4.444444
                                        0700-0759        2.807692
                                        0800-0859        9.945455
                                        0900-0959        7.656250
                                                          ...
12     7            WN                  1800-1859       13.581395
                                        1900-1959       20.972222
                                        2000-2059       18.525000
                                        2100-2159       23.854167
                                        2200-2259        8.428571
Name: ARR_DELAY_NEW, Length: 1501, dtype: float64

In [9]:
avg_arr_delays = []
for row in MCI_origin_df.iterrows():
    month = row[1]['MONTH']
    dow = row[1]['DAY_OF_WEEK']
    carrier = row[1]['MKT_UNIQUE_CARRIER']
    time = row[1]['DEP_TIME_BLK']
    try:
        avg_arr_delay = avg_arr_delay_dict[month][dow][carrier][time]
        avg_arr_delays.append(avg_arr_delay)
    except:
        avg_arr_delays.append(12)

In [60]:
MCI_origin_df['AVG_ARR_DELAY']=avg_arr_delays

In [61]:
MCI_origin_df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_UNIQUE_CARRIER,MKT_CARRIER_FL_NUM,TAIL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,...,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,Status,DATE,DEST_LAT,DEST_LON,ORIGIN_LAT,ORIGIN_LON,AVG_ARR_DELAY
29,2021,1,1,5,WN,2346,A,MCI,Kansas City,Missouri,...,7.0,1500-1559,0.0,Delayed,2021-01-01,33.748992,-84.390264,39.100105,-94.578142,2.928571
30,2021,1,1,5,WN,2470,V,MCI,Kansas City,Missouri,...,-1.0,1300-1359,0.0,On Time,2021-01-01,32.776272,-96.796856,39.100105,-94.578142,5.000000
31,2021,1,1,5,WN,2493,N,MCI,Kansas City,Missouri,...,0.0,1100-1159,0.0,Delayed,2021-01-01,32.776272,-96.796856,39.100105,-94.578142,2.526316
32,2021,1,1,5,WN,2776,Z,MCI,Kansas City,Missouri,...,2.0,1300-1359,0.0,Delayed,2021-01-01,39.290882,-76.610759,39.100105,-94.578142,2.526316
33,2021,1,1,5,WN,2800,B,MCI,Kansas City,Missouri,...,1.0,1500-1559,0.0,Delayed,2021-01-01,32.776272,-96.796856,39.100105,-94.578142,6.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129816,2023,12,31,7,WN,673,Q,MCI,Kansas City,Missouri,...,-2.0,1100-1159,0.0,On Time,2023-12-31,43.034993,-87.922497,39.100105,-94.578142,9.895833
129817,2023,12,31,7,WN,714,A,MCI,Kansas City,Missouri,...,-1.0,1000-1059,0.0,On Time,2023-12-31,41.875562,-87.624421,39.100105,-94.578142,14.328358
129818,2023,12,31,7,WN,846,Z,MCI,Kansas City,Missouri,...,-1.0,1700-1759,0.0,Delayed,2023-12-31,29.424600,-98.495141,39.100105,-94.578142,20.074074
129819,2023,12,31,7,WN,894,N,MCI,Kansas City,Missouri,...,-1.0,1800-1859,0.0,Delayed,2023-12-31,38.631966,-90.242876,39.100105,-94.578142,33.275000
129820,2023,12,31,7,WN,998,A,MCI,Kansas City,Missouri,...,-1.0,1400-1459,0.0,Delayed,2023-12-31,39.739236,-104.984862,39.100105,-94.578142,32.321429

In [62]:
X_origin = MCI_origin_df[['MONTH','DAY_OF_MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER','TAIL_NUM', 'DEST', 'DEP_TIME_BLK','AVG_ARR_DELAY']]

In [63]:
X_origin

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_UNIQUE_CARRIER,TAIL_NUM,DEST,DEP_TIME_BLK,AVG_ARR_DELAY
29,1,1,5,WN,A,ATL,1200-1259,2.928571
30,1,1,5,WN,V,DAL,1100-1159,5.000000
31,1,1,5,WN,N,DAL,0900-0959,2.526316
32,1,1,5,WN,Z,BWI,0900-0959,2.526316
33,1,1,5,WN,B,DAL,1400-1459,6.533333
...,...,...,...,...,...,...,...,...
129816,12,31,7,WN,Q,MKE,0900-0959,9.895833
129817,12,31,7,WN,A,MDW,0800-0859,14.328358
129818,12,31,7,WN,Z,SAT,1500-1559,20.074074
129819,12,31,7,WN,N,STL,1700-1759,33.275000
129820,12,31,7,WN,A,DEN,1300-1359,32.321429

In [64]:
X_origin.describe()

              MONTH  DAY_OF_MONTH   DAY_OF_WEEK  AVG_ARR_DELAY
count  54461.000000  54461.000000  54461.000000   54461.000000
mean       6.886543     15.794642      3.985476      13.017524
std        3.330503      8.778920      2.007000      10.425937
min        1.000000      1.000000      1.000000       0.000000
25%        4.000000      8.000000      2.000000       5.300000
50%        7.000000     16.000000      4.000000      10.142857
75%       10.000000     23.000000      6.000000      18.612245
max       12.000000     31.000000      7.000000      66.500000

In [14]:
avg_arr_delay_blks = []
for row in X_origin.iterrows():
    avg_arr_delay = row[1]['AVG_ARR_DELAY'] 
    if avg_arr_delay <= 5.300000:
        avg_arr_delay_blk = '0-25%'
    elif avg_arr_delay <= 10.142857:
        avg_arr_delay_blk = '25-50%'
    elif avg_arr_delay <= 18.612245:
        avg_arr_delay_blk = '50-75%'
    else:
        avg_arr_delay_blk = '75-100%'
    avg_arr_delay_blks.append(avg_arr_delay_blk)

In [65]:
avg_arr_delay_blks

['0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '25-50%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '75-100%',
 '0-25%',
 '75-100%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '50-75%',
 '50-75%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '50-75%',
 '75-100%',
 '75-100%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '75-100%',
 '75-100%',
 '50-75%',
 '0-25%',
 '75-100%',
 '25-50%',
 '50-75%',
 '0-25%',
 '75-100%',
 '25-50%',
 '75-100%',
 '25-50%',
 '25-50%',
 '75-100%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '75-100%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '25-50%',
 '25-50%',
 '75-100%',
 '0-25%',
 '75-100%',
 '0-25%',
 '25-50%',
 '25-50%',
 '75-100%',
 '75-100%',
 '25-50%',
 '75-100%',
 '0-25%',
 '75-100%',
 '50-75%',
 '50-75%',
 '50-75%',
 '50-75%',
 '50-75%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '50-75%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '75-100%',
 '25-50%',
 '25-50%',
 '0-25%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '0-25%',
 '50-75%',
 '25-50%',
 '0-25%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '75-100%',
 '50-75%',
 '75-100%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '75-100%',
 '50-75%',
 '25-50%',
 '50-75%',
 '75-100%',
 '25-50%',
 '75-100%',
 '75-100%',
 '75-100%',
 '50-75%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '75-100%',
 '75-100%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '50-75%',
 '0-25%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '75-100%',
 '25-50%',
 '75-100%',
 '25-50%',
 '50-75%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '0-25%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '50-75%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '25-50%',
 '75-100%',
 '50-75%',
 '25-50%',
 '75-100%',
 '75-100%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '50-75%',
 '25-50%',
 '75-100%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '75-100%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '50-75%',
 '0-25%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '75-100%',
 '25-50%',
 '75-100%',
 '25-50%',
 '50-75%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '0-25%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '50-75%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '25-50%',
 '75-100%',
 '50-75%',
 '25-50%',
 '75-100%',
 '75-100%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '50-75%',
 '25-50%',
 '75-100%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '75-100%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '50-75%',
 '0-25%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '75-100%',
 '25-50%',
 '75-100%',
 '25-50%',
 '50-75%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '0-25%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '50-75%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '25-50%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '25-50%',
 '75-100%',
 '50-75%',
 '25-50%',
 '75-100%',
 '75-100%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '75-100%',
 '50-75%',
 '25-50%',
 '75-100%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '75-100%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '50-75%',
 '0-25%',
 '50-75%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '75-100%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '75-100%',
 '25-50%',
 '75-100%',
 '25-50%',
 '50-75%',
 '0-25%',
 '25-50%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '50-75%',
 '0-25%',
 '50-75%',
 '50-75%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '75-100%',
 '0-25%',
 '75-100%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '75-100%',
 '50-75%',
 '75-100%',
 '25-50%',
 '75-100%',
 '25-50%',
 '25-50%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '50-75%',
 '50-75%',
 '75-100%',
 '50-75%',
 '50-75%',
 '25-50%',
 '25-50%',
 '50-75%',
 '50-75%',
 '50-75%',
 '0-25%',
 '0-25%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '75-100%',
 '50-75%',
 '75-100%',
 '50-75%',
 '50-75%',
 '0-25%',
 '50-75%',
 '50-75%',
 '0-25%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '25-50%',
 '50-75%',
 '50-75%',
 '50-75%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '0-25%',
 '50-75%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '50-75%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '50-75%',
 '25-50%',
 '50-75%',
 '25-50%',
 '0-25%',
 '0-25%',
 '25-50%',
 '0-25%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '50-75%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '50-75%',
 '0-25%',
 '50-75%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '0-25%',
 '25-50%',
 '25-50%',
 '0-25%',
 ...]

In [66]:
X_origin['AVG_ARR_DELAY']=avg_arr_delay_blks
X_origin

C:\Users\Matt\AppData\Local\Temp\ipykernel_17512\3272398199.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_origin['AVG_ARR_DELAY']=avg_arr_delay_blks

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_UNIQUE_CARRIER,TAIL_NUM,DEST,DEP_TIME_BLK,AVG_ARR_DELAY
29,1,1,5,WN,A,ATL,1200-1259,0-25%
30,1,1,5,WN,V,DAL,1100-1159,0-25%
31,1,1,5,WN,N,DAL,0900-0959,0-25%
32,1,1,5,WN,Z,BWI,0900-0959,0-25%
33,1,1,5,WN,B,DAL,1400-1459,25-50%
...,...,...,...,...,...,...,...,...
129816,12,31,7,WN,Q,MKE,0900-0959,25-50%
129817,12,31,7,WN,A,MDW,0800-0859,50-75%
129818,12,31,7,WN,Z,SAT,1500-1559,75-100%
129819,12,31,7,WN,N,STL,1700-1759,75-100%
129820,12,31,7,WN,A,DEN,1300-1359,75-100%

In [67]:
y_origin = MCI_origin_df[['Status']]

In [68]:
y_origin

         Status
29      Delayed
30      On Time
31      Delayed
32      Delayed
33      Delayed
...         ...
129816  On Time
129817  On Time
129818  Delayed
129819  Delayed
129820  Delayed

[54461 rows x 1 columns]

In [24]:
months = []
days = []
month_dict = {1:'January', 2: 'February',3:'March', 4: 'April',5:'May', 6: 'Jun',7:'July', 8: 'August',9:'September', 10: 'October',11:'November', 12: 'December'}
for row in X_origin.iterrows():
    month = month_dict[row[1]['MONTH']]
    day = f"{row[1]['DAY_OF_MONTH']}"
    days.append(day)
    months.append(month)

In [69]:
X_origin['MONTH'] = months
X_origin['DAY_OF_MONTH'] = days

C:\Users\Matt\AppData\Local\Temp\ipykernel_17512\2036610955.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_origin['MONTH'] = months
C:\Users\Matt\AppData\Local\Temp\ipykernel_17512\2036610955.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_origin['DAY_OF_MONTH'] = days

In [26]:
dows = []
for row in X_origin.iterrows():
    if row[1]['DAY_OF_WEEK'] == 1:
        dow = 'Monday'
    if row[1]['DAY_OF_WEEK'] == 2:
        dow = 'Tuesday'
    if row[1]['DAY_OF_WEEK'] == 3:
        dow = 'Wednesday'
    if row[1]['DAY_OF_WEEK'] == 4:
        dow = 'Thursday'
    if row[1]['DAY_OF_WEEK'] == 5:
        dow = 'Friday'
    if row[1]['DAY_OF_WEEK'] == 6:
        dow = 'Saturday'
    if row[1]['DAY_OF_WEEK'] == 7:
        dow = 'Sunday'
    dows.append(dow)

In [70]:
X_origin['DAY_OF_WEEK'] = dows
X_origin

C:\Users\Matt\AppData\Local\Temp\ipykernel_17512\1292891405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_origin['DAY_OF_WEEK'] = dows

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_UNIQUE_CARRIER,TAIL_NUM,DEST,DEP_TIME_BLK,AVG_ARR_DELAY
29,January,1,Friday,WN,A,ATL,1200-1259,0-25%
30,January,1,Friday,WN,V,DAL,1100-1159,0-25%
31,January,1,Friday,WN,N,DAL,0900-0959,0-25%
32,January,1,Friday,WN,Z,BWI,0900-0959,0-25%
33,January,1,Friday,WN,B,DAL,1400-1459,25-50%
...,...,...,...,...,...,...,...,...
129816,December,31,Sunday,WN,Q,MKE,0900-0959,25-50%
129817,December,31,Sunday,WN,A,MDW,0800-0859,50-75%
129818,December,31,Sunday,WN,Z,SAT,1500-1559,75-100%
129819,December,31,Sunday,WN,N,STL,1700-1759,75-100%
129820,December,31,Sunday,WN,A,DEN,1300-1359,75-100%

In [71]:
X_origin.dtypes

MONTH                 object
DAY_OF_MONTH          object
DAY_OF_WEEK           object
MKT_UNIQUE_CARRIER    object
TAIL_NUM              object
DEST                  object
DEP_TIME_BLK          object
AVG_ARR_DELAY         object
dtype: object

In [72]:
y_origin_dummies = pd.get_dummies(y_origin)
y_origin_dummies

        Status_Delayed  Status_On Time
29                   1               0
30                   0               1
31                   1               0
32                   1               0
33                   1               0
...                ...             ...
129816               0               1
129817               0               1
129818               1               0
129819               1               0
129820               1               0

[54461 rows x 2 columns]

In [73]:
y_origin_dummies.describe()

       Status_Delayed  Status_On Time
count    54461.000000    54461.000000
mean         0.566369        0.433631
std          0.495580        0.495580
min          0.000000        0.000000
25%          0.000000        0.000000
50%          1.000000        0.000000
75%          1.000000        1.000000
max          1.000000        1.000000

In [31]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from keras.layers import Dense, Dropout

WARNING:tensorflow:From C:\Users\Matt\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [74]:
X_origin_dummies = pd.get_dummies(X_origin,drop_first=True)
X_origin_dummies

,MONTH_August,MONTH_December,MONTH_February,MONTH_January,MONTH_July,MONTH_Jun,MONTH_March,MONTH_May,MONTH_November,MONTH_October,...,DEP_TIME_BLK_1600-1659,DEP_TIME_BLK_1700-1759,DEP_TIME_BLK_1800-1859,DEP_TIME_BLK_1900-1959,DEP_TIME_BLK_2000-2059,DEP_TIME_BLK_2100-2159,DEP_TIME_BLK_2200-2259,AVG_ARR_DELAY_25-50%,AVG_ARR_DELAY_50-75%,AVG_ARR_DELAY_75-100%
29,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129816,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
129817,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
129818,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
129819,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
129820,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
scaler = StandardScaler()
scaler.fit(X_origin_dummies)
transformed_data = scaler.transform(X_origin_dummies)
# Creating a DataFrame with with the scaled data
transformed_data_df = pd.DataFrame(transformed_data)

# Display sample data
transformed_data_df

In [ ]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np
pca = PCA().fit(transformed_data_df)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

In [ ]:
from sklearn.decomposition import PCA
# Create a PCA model
nc = 15
pca = PCA(n_components=nc)
pca_data = pca.fit_transform(transformed_data_df)
pca_dict = {}
for i in range(0,nc):
    pca_dict[f'pca{i+1}']=pca_data[:,i]
# Display sample data
pca_df = pd.DataFrame(pca_dict)
pca_df

In [75]:
y_origin_dummies

        Status_Delayed  Status_On Time
29                   1               0
30                   0               1
31                   1               0
32                   1               0
33                   1               0
...                ...             ...
129816               0               1
129817               0               1
129818               1               0
129819               1               0
129820               1               0

[54461 rows x 2 columns]

In [76]:
X_origin_dummies

,MONTH_August,MONTH_December,MONTH_February,MONTH_January,MONTH_July,MONTH_Jun,MONTH_March,MONTH_May,MONTH_November,MONTH_October,...,DEP_TIME_BLK_1600-1659,DEP_TIME_BLK_1700-1759,DEP_TIME_BLK_1800-1859,DEP_TIME_BLK_1900-1959,DEP_TIME_BLK_2000-2059,DEP_TIME_BLK_2100-2159,DEP_TIME_BLK_2200-2259,AVG_ARR_DELAY_25-50%,AVG_ARR_DELAY_50-75%,AVG_ARR_DELAY_75-100%
29,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129816,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
129817,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
129818,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
129819,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
129820,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [77]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X_origin_dummies, y_origin_dummies['Status_On Time'], random_state=78)

In [78]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=64, activation="relu", input_dim=len(X_origin_dummies.columns)))
# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=128, activation="relu"))
nn_model.add(Dropout(0.2))
# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=512, activation="relu"))
nn_model.add(Dropout(0.5))
# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=1024, activation="relu"))
nn_model.add(Dropout(0.7))
# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=512, activation="sigmoid"))
nn_model.add(Dropout(0.5))
nn_model.add(tf.keras.layers.Dense(units=64, activation="sigmoid"))
nn_model.add(Dropout(0.2))
# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_21 (Dense)            (None, 64)                8256

 dense_22 (Dense)            (None, 128)               8320

 dropout_15 (Dropout)        (None, 128)               0

 dense_23 (Dense)            (None, 512)               66048

 dropout_16 (Dropout)        (None, 512)               0

 dense_24 (Dense)            (None, 1024)              525312

 dropout_17 (Dropout)        (None, 1024)              0

 dense_25 (Dense)            (None, 512)               524800

 dropout_18 (Dropout)        (None, 512)               0

 dense_26 (Dense)            (None, 64)                32832

 dropout_19 (Dropout)        (None, 64)                0

 dense_27 (Dense)            (None, 1)                 65

=================================================================
Total params: 1165633 (4.45 MB)
Trainable params: 1165633 (4.45 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [79]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [80]:
# Train the model
fit_model = nn_model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1277/1277 [==============================] - 5s 3ms/step - loss: 0.6579 - accuracy: 0.6139
Epoch 2/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.6367 - accuracy: 0.6443
Epoch 3/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.6286 - accuracy: 0.6526
Epoch 4/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.6179 - accuracy: 0.6635
Epoch 5/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.6070 - accuracy: 0.6762
Epoch 6/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.5955 - accuracy: 0.6890
Epoch 7/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.5871 - accuracy: 0.6985
Epoch 8/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.5783 - accuracy: 0.7056
Epoch 9/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.5705 - accuracy: 0.7137
Epoch 10/10
1277/1277 [==============================] - 4s 3ms/step - loss: 0.5608 - accuracy: 0.7209

In [81]:
model_loss, model_accuracy = nn_model.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

426/426 - 0s - loss: 0.6643 - accuracy: 0.6361 - 497ms/epoch - 1ms/step
Loss: 0.6642572283744812, Accuracy: 0.6360899209976196

In [ ]:
predictions = nn_model.predict(X_test)
predictions

In [ ]:
y_test

In [ ]:
predictions_df

In [ ]:
predictions_df = pd.DataFrame(predictions.tolist())
predictions_df.describe()

In [ ]:
nn_model.save('../nn_model.keras')

In [ ]:
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(random_state=1)

# Fit the model using training data
model.fit(X_train, y_train)

In [ ]:
model.score(X_train, y_train)

In [ ]:
# Make a prediction using the testing data
predictions = model.predict(X_test)
# Print the balanced_accuracy score of the model
balanced_accuracy_score(y_test,predictions)

In [ ]:
# Generate a confusion matrix for the model
confusion_matrix(y_test,predictions)

In [ ]:
# Print the classification report for the model
tn, fp, fn, tp = confusion_matrix(y_test, predictions).ravel()
accuracy = (tp + tn) / (tp + fp + tn + fn)
accuracy

In [ ]:
tp

In [ ]:
tn

In [ ]:
fp

In [ ]:
fn